name: Automation Tests (API & Web UI)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Run API and Web UI Automation Tests
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up JDK
    - name: Set up JDK 23
      uses: actions/setup-java@v3
      with:
        distribution: 'oracle'
        java-version: '23'
        cache: 'gradle'

      #setup gradle
    - name: execute with gradle
      run: chmod +x gradlew

    # Step 3: Install dependencies
    - name: Install dependencies
      run: ./gradlew dependencies

    # Step 6: Install Google Chrome and ChromeDriver for UI tests
    - name: Install Google Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        
    - name: Install ChromeDriver
      run: |
        CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | awk -F '.' '{print $1}')
        DRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
        wget -N "https://chromedriver.storage.googleapis.com/$DRIVER_VERSION/chromedriver_linux64.zip" -P ~/
        unzip ~/chromedriver_linux64.zip -d ~/
        sudo mv -f ~/chromedriver /usr/local/bin/chromedriver
        sudo chmod 0755 /usr/local/bin/chromedriver

    # Step 7: Run  tests
    - name: Run tests
      run: ./gradlew clean test

    # Step 8: Upload test reports as artifacts
    - name: archive test results
      uses: actions/upload-artifact@v4.3.0
      if: always()
      with:
        name: cucumber reports
        path: target/cucumber-reports.html

