name: Automation Tests (API & Web UI)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Run API and Web UI Automation Tests
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up JDK
    - name: Set up JDK 23
      uses: actions/setup-java@v3
      with:
        distribution: 'oracle'
        java-version: '23'
        cache: 'gradle'

      #setup gradle
    - name: execute with gradle
      run: chmod +x gradlew

    # Step 3: Install dependencies
    - name: Install dependencies
      run: ./gradlew dependencies

    # Step 6: Install Google Chrome and ChromeDriver for UI tests
    - name: Install Google Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        
    - name: Install ChromeDriver
      uses: browser-actions/setup-chrome@v0.0.0
      with:
    # The Google Chrome/Chromium version to install and use.
        chrome-version: latest

    - name: Debug Chrome and ChromeDriver versions
      run: |
        echo "Google Chrome version:"
        google-chrome --version
        echo "ChromeDriver version:"
        chromedriver --version || echo "ChromeDriver not found"

    # Step 7: Run  tests
    - name: Run tests
      run: ./gradlew clean test

    # Step 8: Upload test reports as artifacts
    - name: archive test results
      uses: actions/upload-artifact@v4.3.0
      if: always()
      with:
        name: cucumber reports
        path: target/cucumber-reports.html

