name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up JDK
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'

    # Step 3: Download and set up Chrome
    - name: Install Google Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    # Step 4: Set up ChromeDriver
    - name: Setup Chrome
     # uses: browser-actions/setup-chrome@facf10a55b9caf92e0cc749b4f82bf8220989148
      uses: browser-actions/setup-chrome@v1.7.2
      with:
    # The Google Chrome/Chromium version to install and use.
        chrome-version: latest # optional, default is latest
    # Install dependent packages for Google Chrome/Chromium (Linux only).
        install-dependencies: optional
    # Install the compatible version of ChromeDriver with the installed Google Chrome/Chromium.
        install-chromedriver: optional
    # Do not use sudo to install Google Chrome/Chromium (Linux only).
        no-sudo: optional

    # Step 5: Set ChromeDriver path
    - name: Set ChromeDriver path
      run: echo "CHROMEDRIVER_PATH=C:\Learning\chromedriver-win64\chromedriver.exe" >> $GITHUB_ENV

    - name: execute with gradle
      run: chmod +x gradlew

    # Step 6: Build and test project
    - name: Build and test project
      run: ./gradlew test

    # Step 7: Upload test report
    - name: Upload test report
      uses: actions/upload-artifact@v3
      with:
        name: cucumber-reports
        path: build/reports/tests/test/
