name: Automation API and web UI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  set-up_automation_test:

    runs-on: ubuntu-latest

    steps:
    # download reepository
    - uses: actions/checkout@v4

    #setup java
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'

    #install browser
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v0.0.0

    #setup gradew
    - name: Setup gradlew
      run:  chmod +x gradlew

    #exceute gradlew command for running cucumber test
    - name: Execute Test
      run: ./gradlew test
