name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Java environment
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      # Step 3: Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Step 4: Install Chrome browser
      - name: Install Chrome
        run: sudo apt-get install -y google-chrome-stable

      # Step 5: Setup ChromeDriver
      - name: Setup ChromeDriver
        uses: browser-actions/setup-chrome@v1
        with:
          version: latest

      #setup gradle
      - name: execute with gradle
        run: chmod +x gradlew

      # Step 6: Build the project
      - name: Build the project
        run: ./gradlew build

      # Step 7: Run Cucumber tests
      - name: Run Cucumber Tests
        run: ./gradlew test

      # Step 8: Upload Test Results
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: build/test-results/
