name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Java environment
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      # Step 3: Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Step 4: Download and install ChromeDriver
      - name: Setup ChromeDriver
        uses: nanasess/setup-chromedriver@v1
        with:
          version: latest

      # Step 5: Install Chrome browser
      - name: Install Chrome
        run: sudo apt-get install -y google-chrome-stable

      # Step 6: Verify Gradle build
      - name: Build with Gradle
        run: ./gradlew build

      # Step 7: Run Cucumber tests
      - name: Run Cucumber tests
        run: ./gradlew test

      - name: archive test results
        uses: actions/upload-artifact@v4.3.0
        if: always()
        with:
          name: cucumber reports
          path: target/cucumber-reports.html
