name: Run JunitCI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write


jobs:
  automationJunit:

    runs-on: ubuntu-latest

    steps:
    # download reepository
    - uses: actions/checkout@v3

    #setup java
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'

    #install browser
    - name: Setup Chrome with extra capabilities
      uses: browser-actions/setup-chrome@v1.4.0
      with: 
        chrome-version: latest

    #setup gradle
    - name: execute with gradle
      run: chmod +x gradlew

    - name: Build with gradle
      run: ./gradlew build
          
    #exceute gradlew command for running cucumber test
    - name: Run Test
      run: ./gradlew clean test

    - name: archive test results
      uses: actions/upload-artifact@v4.3.0
      if: always()
      with:
        name: cucumber reports
        path: target/cucumber-reports.html
